version: "3.5"
services:
  php-fpm:
    build:
      context: .
      dockerfile: php-fpm/Dockerfile
      args:
        - LOCAL_UID=${LOCAL_UID}
        - LOCAL_GID=${LOCAL_GID}
    depends_on:
      - mysql
    volumes:
      - ${SYMFONY_APP_PATH}:/application
      - ./php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/infrastructure-overrides.ini
  marvel-api:
    image: nginx:alpine
    container_name: marvel-api
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${SYMFONY_APP_PATH}:/application
  mysql:
    build:
      context: .
      dockerfile: mysql/Dockerfile
      args:
        - LOCAL_UID=${LOCAL_UID}
        - LOCAL_GID=${LOCAL_GID}
    volumes:
      - "./database:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
      - PMA_HOST=mysql
    depends_on:
      - mysql
  angular:
    image: angular
    build:
      context: .
      dockerfile: angular/Dockerfile
      args:
        - PROXY=${PROXY}
        - PROXYS=${PROXYS}
    volumes:
      - ../application/:/application
    ports:
      - "4200:4200"